apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-demo-client
spec:
  selector:
    matchLabels:
      app: react-demo-client
  template:
    metadata:
      labels:
        app: react-demo-client
    spec:
      containers:
      - name: react-demo-client
        image: walk1ng/react-ts-demo-client:v1
        ports:
        - containerPort: 7070
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
        env:
        - name: API_URL
          value: react-demo-server.kustomize-react-demo-server-db.svc
