apiVersion: batch/v1
kind: Job
metadata:
  name: postsync-hook
  annotations:
    argocd.argopro.io/hook: PostSync
    argocd.argopro.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: cleanup
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sleep", "5"]
      restartPolicy: Never
