# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  repository_dispatch:
    types:    # 可以自定义事件类型
      - trigger-b

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      image:
        required: true
        description: 'docker image name'
      sha-tag:
        required: true
        description: 'docker image tag'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        if: ${{ github.event.client_payload.image }}
      
      - name: kustomize edit
        if: ${{ github.event.client_payload.image }}
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
          kustomize edit set image ${{ github.event.client_payload.image }}:${{ github.event.client_payload.sha-tag }}
          rm -f kustomize
      
      - name: Git Commit/Push Changes
        uses: actions-x/commit@v6
        if: ${{ github.event.client_payload.image }}
        with:
          message: "kustomize set image to ${{ github.event.client_payload.image }}:${{ github.event.client_payload.sha-tag }}"
          branch: refs/heads/main
          email: iliwgg@gmail.com
